---
new_page_extension: md
auto_deploy: true
admin_path: forestry
webhook_url: 
sections:
- type: directory
  path: content/pieces
  label: Pieces
  create: all
  match: "**/*"
- type: directory
  path: content/piles
  label: Piles
  create: all
  match: "**/*"
- type: directory
  path: content/influences
  label: Influences
  create: all
  match: "**/*"
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
- type: directory
  path: content/beliefs
  label: Beliefs
  create: all
  match: "**/*"
- type: directory
  path: content/me
  label: Me
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.52
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: '0.52'
